services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3001}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - NODE_ENV=${NODE_ENV:-development}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true