
services:
  api:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 