name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Deploy via SSH
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${USERNAME}@${HOSTNAME} '
            # Navigate to your existing project directory
            cd ~/Portfolio-API &&
            
            # Pull latest changes
            git fetch --all &&
            git reset --hard origin/main &&
            
            # Restart the application with new changes
            docker-compose -f docker-compose.yml down &&
            docker-compose -f docker-compose.yml pull &&
            docker-compose -f docker-compose.yml up -d --build &&
            
            # Clean up old images
            docker image prune -f
          ' 